export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const MARK_COMPLETED = 'MARK_COMPLETED';
export const MARK_INCOMPLETE = 'MARK_INCOMPLETE';
export const FILTER_TASKS = 'FILTER_TASKS';
export const MARK_ALL_COMPLETED = 'MARK_ALL_COMPLETED';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';